# Generated by Django 4.0 on 2022-08-10 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(verbose_name='Like')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('original_name', models.CharField(max_length=50, verbose_name='Original name')),
                ('director', models.CharField(max_length=30, verbose_name='Director')),
                ('genre', models.CharField(max_length=10, verbose_name='Genre')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=6, verbose_name='Password')),
                ('photo', models.ImageField(upload_to='', verbose_name='Photo')),
                ('movies', models.ManyToManyField(through='movies.Like', to='movies.Movie')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.AddField(
            model_name='like',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.movie', verbose_name='Movie'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.user', verbose_name='User'),
        ),
    ]
