# Generated by Django 4.0 on 2022-08-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='photo',
            field=models.ImageField(default='', upload_to='', verbose_name='Photo'),
        ),
    ]
